version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - app-network

  web:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: >
      bash -c "
        ./wait-for-it.sh db:5432 -- alembic upgrade head &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

networks:
  app-network:
    driver: bridge
